name: Deploy a Hostinger 🚀
on:
  push:
    branches:
      - main  # Asegúrate de que tu rama principal se llama 'main'. Si es 'master', cambia esto a 'master'.

jobs:
  web-deploy:
    name: 🎉 Subiendo a Hostinger
    runs-on: ubuntu-latest
    steps:
    - name: 🚚 Obtener código más reciente
      uses: actions/checkout@v4
    
    - name: 📂 Sincronizar archivos (FTP)
      uses: SamKirkland/FTP-Deploy-Action@v4.3.5
      with:
        server: ${{ secrets.FTP_SERVER }}
        username: ${{ secrets.FTP_USERNAME }}
        password: ${{ secrets.FTP_PASSWORD }}
        server-dir: ./public_html/
        # Esto borrará archivos en el servidor que no existan en tu git (limpieza automática)
        delete: true 
        exclude: |
          **/.git*
          **/.github*
          README.md