name: Deploy a Hostinger 🚀
on:
  push:
    branches:
      - main  # Asegúrate de que tu rama se llama 'main'

jobs:
  web-deploy:
    name: 🎉 Subiendo a Hostinger
    runs-on: ubuntu-latest
    steps:
    - name: 🚚 Obtener código más reciente
      uses: actions/checkout@v4
    
    - name: 📂 Sincronizar archivos (FTP)
      uses: SamKirkland/FTP-Deploy-Action@v4.3.5
      with:
        server: ${{ secrets.FTP_SERVER }}
        username: ${{ secrets.FTP_USERNAME }}
        password: ${{ secrets.FTP_PASSWORD }}
        server-dir: ./
        # Al poner ./ le decimos que lo suelte todo en la raíz del usuario FTP
        delete: true 
        exclude: |
          **/.git*
          **/.github*
          README.md